template_variables:
  product_full: Md2Docs Test Bed
  product_short: Md2Docs
  app_runtime_full: Md 2 Docs Test Bed APPRUNTIME full
  current_version: 1
  max_version: 1
  platform_code: CF
  path_to_partials: /partials
  support_link: <a href="http://support.pivotal.io" target="_blank">Support</a>
  metrics:
    -
      tag: cm
      unit: cm
      description: Metric in CMs
      source: here
    -
      tag: mm
      unit: mm
      description: Metric in MMs
      source: there