template_variables:
  products_AWA: Automic Automation
  products_AWA_FirstMention: Automic Automation
  products_AWA_Old: Automic Workload Automation
  products_AWA_Old_short: AWA
  products_AWA_short: Automic Automation
