conditions:
  ProductVersionConditions_24_1_0: true
  ProductVersionConditions_24_3_0: true
  ProductVersionConditions_24_4_0: true
  ProductVersionConditions_AWA_12_0_0: true
  guideConditions_ARA: true
  guideConditions_AWA: true
  guideConditions_AWI: true
  guideConditions_NotInAIOps: true
  guideConditions_NotInAIR: true
  guideConditions_OnlyInAIR: true
  guideTypeConditions_CSH_DoNotRename: true
  mediaConditions_ScreenOnly: true
  statusConditions_Deprecated: true
  statusConditions_DoNotTranslate: true
  statusConditions_MoveToAEM: true
  statusConditions_Planned: true
  statusConditions_ScriptReviewed: true
product_names:
  3rdPartyNames_AWS: "AWS"
  3rdPartyNames_AWS_Batch: "AWS Batch"
  3rdPartyNames_AWS_EMR_long: "AWS EMR"
  3rdPartyNames_AWS_EMR_short: "EMR"
  3rdPartyNames_AWS_Glue_long: "AWS Glue"
  3rdPartyNames_AWS_Lambda: "AWS Lambda"
  3rdPartyNames_AWS_S3: "AWS S3"
  3rdPartyNames_AWS_StepFunctions: "AWS Step Functions"
  3rdPartyNames_Amazon: "Amazon"
  3rdPartyNames_AmazonS3: "Amazon S3"
  3rdPartyNames_Amazon_EventBridge: "Amazon EventBridge"
  3rdPartyNames_ApacheTomcatName: "Tomcat"
  3rdPartyNames_Apache_Airflow: "Apache Airflow"
  3rdPartyNames_Apache_Hadoop: "Apache Hadoop"
  3rdPartyNames_Apache_Kafka: "Apache Kafka"
  3rdPartyNames_AtlassianJiraName: "JIRA"
  3rdPartyNames_Azure: "Azure"
  3rdPartyNames_AzureBlob: "Azure Blob Storage"
  3rdPartyNames_AzureDataFactory: "Azure Data Factory"
  3rdPartyNames_AzureDatabricks_alone: "Databricks"
  3rdPartyNames_AzureEventGrid: "Azure Event Grid"
  3rdPartyNames_AzureOpenAI: "Azure OpenAI"
  3rdPartyNames_AzureSynapse_complete: "Azure Synapse Analytics"
  3rdPartyNames_AzureSynpase_alone: "Synapse"
  3rdPartyNames_Azure_Functions: "Azure Functions"
  3rdPartyNames_Azure_LogicApps: "Azure Logic Apps"
  3rdPartyNames_Azure_Logic_Apps: "Azure Logic Apps"
  3rdPartyNames_Azure_Synapse: "Azure Synapse"
  3rdPartyNames_BlockBlob: "Block Blob"
  3rdPartyNames_CA_Automic: "Automic"
  3rdPartyNames_DataFactory_alone: "Data Factory"
  3rdPartyNames_Databricks: "Databricks"
  3rdPartyNames_Docker: "Docker"
  3rdPartyNames_EPM_alone: "EPM"
  3rdPartyNames_Eclipse: "Eclipse"
  3rdPartyNames_Equinox: "Equinox"
  3rdPartyNames_EventBridge_alone: "EventBridge"
  3rdPartyNames_EventGrid_alone: "Event Grid"
  3rdPartyNames_GCP_BigQuery: "GCP BigQuery"
  3rdPartyNames_GCP_BigQuery_short: "BigQuery"
  3rdPartyNames_GIT: "GIT"
  3rdPartyNames_GKE_short: "GKE"
  3rdPartyNames_Gemini: "Gemini"
  3rdPartyNames_GoogleCloud: "Google Cloud Platform"
  3rdPartyNames_Google_Cloud_Batch_long: "Google Cloud Batch"
  3rdPartyNames_Google_Cloud_Run: "Google Cloud Run"
  3rdPartyNames_IICS_complete: "Informatica Intelligent Cloud Services (IICS)"
  3rdPartyNames_IICS_short: "IICS"
  3rdPartyNames_Informatica_alone: "Informatica"
  3rdPartyNames_Java: "Java"
  3rdPartyNames_Jetty: "Jetty"
  3rdPartyNames_Kubernetes: "Kubernetes"
  3rdPartyNames_Kubernetes_short: "K8s"
  3rdPartyNames_LDAPS: "LDAPS"
  3rdPartyNames_Ldap: "LDAP"
  3rdPartyNames_MWAA: "MWAA"
  3rdPartyNames_Microsoft: "Microsoft"
  3rdPartyNames_OCI_long: "Oracle Cloud Infrastructure"
  3rdPartyNames_OCI_short: "OCI"
  3rdPartyNames_OIC_long: "Oracle Integration Cloud"
  3rdPartyNames_OIC_short: "OIC"
  3rdPartyNames_OSGi: "OSGi"
  3rdPartyNames_Oracle_EPM_long: "Oracle Enterprise Performance Management (EPM)"
  3rdPartyNames_Oracle_EPM_short: "Oracle EPM"
  3rdPartyNames_Oracle_ERP_cloud_short: "Oracle Fusion Cloud ERP"
  3rdPartyNames_Oracle_Fusion_ERP_Cloud_long: "Oracle Fusion Cloud Enterprise Resource Planning"
  3rdPartyNames_PostgreSQL: "PostgreSQL"
  3rdPartyNames_PowerPC_LE: "PowerPC 64 LE"
  3rdPartyNames_SAP_BOBI_long: "SAP BusinessObjects Business Intelligence"
  3rdPartyNames_SAP_BOBI_short: "SAP BOBI"
  3rdPartyNames_SAP_BTP: "SAP BTP"
  3rdPartyNames_SAP_IBP: "SAP Integrated Business Planning (IBP)"
  3rdPartyNames_SAP_IBP_short: "SAP IBP"
  3rdPartyNames_SAP_Integration_Suite: "SAP Integration Suite"
  3rdPartyNames_SiebelCompanyName: "Oracle"
  3rdPartyNames_SnName: "ServiceNow"
  3rdPartyNames_VCF_long: "VMware Cloud Foundation"
  3rdPartyNames_VCF_short: "VCF"
  3rdPartyNames_VMwareName: "VMware"
  3rdPartyNames_WebLogicCompanyName: "Oracle"
  3rdPartyNames_WebLogicName: "WebLogic"
  3rdPartyNames_WebSphere: "WebSphere"
  3rdPartyNames_YouTube: "YouTube"
  ARARolesTemp_araadministrators: "Administrator"
  ARARolesTemp_araapplicationdevelopers: "Application Developer"
  ARARolesTemp_aramanagers: "Manager"
  ARARolesTemp_araoperators: "Operator"
  ARARolesTemp_cddreleasemanagers: "Release Manager"
  DocumentVariables_CompanyName: "Automic"
  DocumentVariables_ProductName: "Automic Automation"
  DocumentVariables_ProductParentName: "Automic System"
  FilePaths_customer_configPathARA: "Automic\\Release.Manager\\WebUI\\customer.config"
  Products_AAI: "Automation Analytics and Intelligence"
  Products_AAI_AA_Connector: "Automic Connector"
  Products_AAI_short: "AAI"
  Products_AAKE: "Automic Automation Kubernetes Edition"
  Products_AAKE_short: "AAKE"
  Products_AE: "Automation Engine"
  Products_AE_FirstMention: "Automation Engine (AE)"
  Products_AE_short: "AE"
  Products_AIR: "Automic Intelligent Remediation"
  Products_AM: "Automic Applications Manager"
  Products_ARA: "Continuous Delivery Automation"
  Products_ARA_ThirdParty_Short: "ARA"
  Products_ARA_short: "CDA"
  Products_ASO: "Automic Service Orchestration"
  Products_AWA: "Automic Automation"
  Products_AWA_FirstMention: "Automic Automation"
  Products_AWA_Old: "Automic Workload Automation"
  Products_AWA_Old_short: "AWA"
  Products_AWA_short: "Automic Automation"
  Products_AWI: "Automic Web Interface"
  Products_AWI_short: "AWI"
  Products_AWS: "AWS"
  Products_AWS_Lambda: "AWS Lambda"
  Products_AaaS: "Analytics"
  Products_ActionBuilder: "Action Builder"
  Products_Airflow: "Airflow"
  Products_Ansible_Tower: "Ansible Tower"
  Products_AutomationAI: "Automation.AI"
  Products_Automic_Docs_URL: "https://docs.automic.com/documentation"
  Products_Automic_SaaS: "Automic SaaS"
  Products_Avaloq: "Avaloq"
  Products_BSA: "Broadcom Software Academy"
  Products_Broadcom: "Broadcom"
  Products_Broadcom_ALLCAPS: "BROADCOM"
  Products_CASC: "Service Catalog"
  Products_CASC_Plugin: "Service Catalog Plug‑in"
  Products_CA_Service_Mgmt: "Service Management"
  Products_CV: "Process Analytics"
  Products_DLC: "https://downloads.automic.com/"
  Products_DXI: "DX Operational Intelligence"
  Products_DXI_FirstMention: "(Undefined variable: Products.DXI_FirstMention)"
  Products_DXP: "DX Platform"
  Products_ESA: "Broadcom Software Academy"
  Products_Email_Agent: "Email Agent"
  Products_Email_Integration: "Email Integration"
  Products_Environment_Manager: "Infrastructure Manager"
  Products_EventEngine: "Event Engine"
  Products_GCC: "Google Cloud Composer"
  Products_GCC_short: "GC Composer"
  Products_GCP_DataFusion: "GCP Data Fusion"
  Products_GCP_DataFusion_short: "Data Fusion"
  Products_GCP_Dataflow: "GCP Dataflow"
  Products_GCP_Dataflow_short: "Dataflow"
  Products_GenAI: "Gen AI"
  Products_Google_Dataproc_long: "Google Dataproc"
  Products_ICE_Admin_long: "Lattice Admin tool"
  Products_ICE_Admin_short: "Lattice Admin Tool"
  Products_ICE_Custom: "Custom Content"
  Products_ICE_Custom_Long: "Automic Automation Custom Help"
  Products_ICE_long: "Automic Automation Help"
  Products_ICE_short: "Help"
  Products_Java_API: "AE.ApplicationInterface"
  Products_LRT: "License Reporting Tool"
  Products_Lambda: "Lambda"
  Products_LdapSync: "LDAP Sync"
  Products_Marketplace: "https://marketplace.automic.com/"
  Products_OAuth: "OAuth"
  Products_PCO: "Policy Orchestrator"
  Products_PDA: "Predictive Analytics"
  Products_PROXY: "Proxy"
  Products_PackMgr: "Package Manager"
  Products_PackMgr_short: "APM"
  Products_PlatformName: "Automic system"
  Products_PlatformName_TitleCase: "Automic System"
  Products_PluginManager: "Plugin Manager"
  Products_RA: "Rapid Automation"
  Products_RA_BANNER: "RA Banner Agent"
  Products_RA_BO: "RA Business Objects Agent"
  Products_RA_FTP: "RA FTP Agent"
  Products_RA_HADOOP: "RA Hadoop Agent"
  Products_RA_HYPERION_EPMA: "RA Hyperion EPMA Agent"
  Products_RA_HYPERION_ESSBASE: "RA Hyperion ESSBASE Agent"
  Products_RA_HYPERION_FDMEE: "RA Hyperion FDMEE Agent"
  Products_RA_HYPERION_FM: "RA Hyperion FM Agent"
  Products_RA_HYPERION_PLANNING: "RA Hyperion Planning Agent"
  Products_RA_INFORMATICA: "RA Informatica Agent"
  Products_RA_JDE: "RA JD Edwards Agent"
  Products_RA_JMS: "RA JMS Agent"
  Products_RA_OPALIS: "RA Microsoft Opalis Agent"
  Products_RA_ORACLE_BUSINESS: "RA Oracle E-Business Suite Agent"
  Products_RA_ORACLE_RETAIL: "RA Oracle Retail Agent"
  Products_RA_Oracle_ERP_Cloud: "RA Oracle ERP Cloud Agent"
  Products_RA_WEBSERVICE_REST: "RA Web Service REST Agent"
  Products_RA_WEBSERVICE_SOAP: "RA Web Service SOAP Agent"
  Products_RA_short: "RA"
  Products_RM: "Request Manager"
  Products_RM_short: "RM"
  Products_S3: "Simple Storage Service"
  Products_S3_short: "S3"
  Products_SAPI: "Service API"
  Products_SAP_Data_Intelligence: "SAP Data Intelligence"
  Products_SNSC: "ServiceNow Service Connector"
  Products_SVO: "Service Orchestrator"
  Products_UIM: "Unified Infrastructure Management"
  Products_UIM_short: "UIM"
  Tools_AIAssistant: "Automation Assistant"
  Tools_CAU: "Centralized Agent Upgrade (CAU)"
  Tools_CAU_short: "CAU"
  Tools_Chatbot: "Intelligent Assistant"
  Tools_CompChecker: "compatibility matrix"
  Tools_Gateway: "TLS Gateway"
  Tools_IMRESTAPIPort: "9000 TCP"
  Tools_Installer: "ONE Installer"
  Tools_Scripting: "Automation Engine scripting language"
  Tools_ZDU: "Zero Downtime Upgrade"
  Tools_ZDU_short: "ZDU"
  UIElements_ARA_Perspective: "Release Automation"
  UIElements_Administration: "Administration"
  UIElements_ProcessAssembly: "Process Assembly"
  UIElements_ProcessMonitoring: "Process Monitoring"
  UIElements_SC: "My Catalog"
  UIElements_VersionManagement: "Version Control"
