conditions:
  productVersionConditions_24_1_0: true
  productVersionConditions_24_3_0: true
  productVersionConditions_24_4_0: true
  productVersionConditions_AWA_12_0_0: true
  guideConditions_ARA: true
  guideConditions_AWA: true
  guideConditions_AWI: true
  guideConditions_NotInAIOps: true
  guideConditions_NotInAIR: true
  guideConditions_OnlyInAIR: true
  guideTypeConditions_CSH_DoNotRename: true
  mediaConditions_ScreenOnly: true
  statusConditions_Deprecated: true
  statusConditions_DoNotTranslate: true
  statusConditions_MoveToAEM: true
  statusConditions_Planned: true
  statusConditions_ScriptReviewed: true
product_names:
  3rdPartyNames_AWS: "AWS"
  3rdPartyNames_AWS_Batch: "AWS Batch"
  3rdPartyNames_AWS_EMR_long: "AWS EMR"
  3rdPartyNames_AWS_EMR_short: "EMR"
  3rdPartyNames_AWS_Glue_long: "AWS Glue"
  3rdPartyNames_AWS_Lambda: "AWS Lambda"
  3rdPartyNames_AWS_S3: "AWS S3"
  3rdPartyNames_AWS_StepFunctions: "AWS Step Functions"
  3rdPartyNames_Amazon: "Amazon"
  3rdPartyNames_AmazonS3: "Amazon S3"
  3rdPartyNames_Amazon_EventBridge: "Amazon EventBridge"
  3rdPartyNames_ApacheTomcatName: "Tomcat"
  3rdPartyNames_Apache_Airflow: "Apache Airflow"
  3rdPartyNames_Apache_Hadoop: "Apache Hadoop"
  3rdPartyNames_Apache_Kafka: "Apache Kafka"
  3rdPartyNames_AtlassianJiraName: "JIRA"
  3rdPartyNames_Azure: "Azure"
  3rdPartyNames_AzureBlob: "Azure Blob Storage"
  3rdPartyNames_AzureDataFactory: "Azure Data Factory"
  3rdPartyNames_AzureDatabricks_alone: "Databricks"
  3rdPartyNames_AzureEventGrid: "Azure Event Grid"
  3rdPartyNames_AzureOpenAI: "Azure OpenAI"
  3rdPartyNames_AzureSynapse_complete: "Azure Synapse Analytics"
  3rdPartyNames_AzureSynpase_alone: "Synapse"
  3rdPartyNames_Azure_Functions: "Azure Functions"
  3rdPartyNames_Azure_LogicApps: "Azure Logic Apps"
  3rdPartyNames_Azure_Logic_Apps: "Azure Logic Apps"
  3rdPartyNames_Azure_Synapse: "Azure Synapse"
  3rdPartyNames_BlockBlob: "Block Blob"
  3rdPartyNames_CA_Automic: "Automic"
  3rdPartyNames_DataFactory_alone: "Data Factory"
  3rdPartyNames_Databricks: "Databricks"
  3rdPartyNames_Docker: "Docker"
  3rdPartyNames_EPM_alone: "EPM"
  3rdPartyNames_Eclipse: "Eclipse"
  3rdPartyNames_Equinox: "Equinox"
  3rdPartyNames_EventBridge_alone: "EventBridge"
  3rdPartyNames_EventGrid_alone: "Event Grid"
  3rdPartyNames_GCP_BigQuery: "GCP BigQuery"
  3rdPartyNames_GCP_BigQuery_short: "BigQuery"
  3rdPartyNames_GIT: "GIT"
  3rdPartyNames_GKE_short: "GKE"
  3rdPartyNames_Gemini: "Gemini"
  3rdPartyNames_GoogleCloud: "Google Cloud Platform"
  3rdPartyNames_Google_Cloud_Batch_long: "Google Cloud Batch"
  3rdPartyNames_Google_Cloud_Run: "Google Cloud Run"
  3rdPartyNames_IICS_complete: "Informatica Intelligent Cloud Services (IICS)"
  3rdPartyNames_IICS_short: "IICS"
  3rdPartyNames_Informatica_alone: "Informatica"
  3rdPartyNames_Java: "Java"
  3rdPartyNames_Jetty: "Jetty"
  3rdPartyNames_Kubernetes: "Kubernetes"
  3rdPartyNames_Kubernetes_short: "K8s"
  3rdPartyNames_LDAPS: "LDAPS"
  3rdPartyNames_Ldap: "LDAP"
  3rdPartyNames_MWAA: "MWAA"
  3rdPartyNames_Microsoft: "Microsoft"
  3rdPartyNames_OCI_long: "Oracle Cloud Infrastructure"
  3rdPartyNames_OCI_short: "OCI"
  3rdPartyNames_OIC_long: "Oracle Integration Cloud"
  3rdPartyNames_OIC_short: "OIC"
  3rdPartyNames_OSGi: "OSGi"
  3rdPartyNames_Oracle_EPM_long: "Oracle Enterprise Performance Management (EPM)"
  3rdPartyNames_Oracle_EPM_short: "Oracle EPM"
  3rdPartyNames_Oracle_ERP_cloud_short: "Oracle Fusion Cloud ERP"
  3rdPartyNames_Oracle_Fusion_ERP_Cloud_long: "Oracle Fusion Cloud Enterprise Resource Planning"
  3rdPartyNames_PostgreSQL: "PostgreSQL"
  3rdPartyNames_PowerPC_LE: "PowerPC 64 LE"
  3rdPartyNames_SAP_BOBI_long: "SAP BusinessObjects Business Intelligence"
  3rdPartyNames_SAP_BOBI_short: "SAP BOBI"
  3rdPartyNames_SAP_BTP: "SAP BTP"
  3rdPartyNames_SAP_IBP: "SAP Integrated Business Planning (IBP)"
  3rdPartyNames_SAP_IBP_short: "SAP IBP"
  3rdPartyNames_SAP_Integration_Suite: "SAP Integration Suite"
  3rdPartyNames_SiebelCompanyName: "Oracle"
  3rdPartyNames_SnName: "ServiceNow"
  3rdPartyNames_VCF_long: "VMware Cloud Foundation"
  3rdPartyNames_VCF_short: "VCF"
  3rdPartyNames_VMwareName: "VMware"
  3rdPartyNames_WebLogicCompanyName: "Oracle"
  3rdPartyNames_WebLogicName: "WebLogic"
  3rdPartyNames_WebSphere: "WebSphere"
  3rdPartyNames_YouTube: "YouTube"
  aRARolesTemp_araadministrators: "Administrator"
  aRARolesTemp_araapplicationdevelopers: "Application Developer"
  aRARolesTemp_aramanagers: "Manager"
  aRARolesTemp_araoperators: "Operator"
  aRARolesTemp_cddreleasemanagers: "Release Manager"
  documentVariables_CompanyName: "Automic"
  documentVariables_ProductName: "Automic Automation"
  documentVariables_ProductParentName: "Automic System"
  filePaths_customer_configPathARA: "Automic\\Release.Manager\\WebUI\\customer.config"
  products_AAI: "Automation Analytics and Intelligence"
  products_AAI_AA_Connector: "Automic Connector"
  products_AAI_short: "AAI"
  products_AAKE: "Automic Automation Kubernetes Edition"
  products_AAKE_short: "AAKE"
  products_AE: "Automation Engine"
  products_AE_FirstMention: "Automation Engine (AE)"
  products_AE_short: "AE"
  products_AIR: "Automic Intelligent Remediation"
  products_AM: "Automic Applications Manager"
  products_ARA: "Continuous Delivery Automation"
  products_ARA_ThirdParty_Short: "ARA"
  products_ARA_short: "CDA"
  products_ASO: "Automic Service Orchestration"
  products_AWA: "Automic Automation"
  products_AWA_FirstMention: "Automic Automation"
  products_AWA_Old: "Automic Workload Automation"
  products_AWA_Old_short: "AWA"
  products_AWA_short: "Automic Automation"
  products_AWI: "Automic Web Interface"
  products_AWI_short: "AWI"
  products_AWS: "AWS"
  products_AWS_Lambda: "AWS Lambda"
  products_AaaS: "Analytics"
  products_ActionBuilder: "Action Builder"
  products_Airflow: "Airflow"
  products_Ansible_Tower: "Ansible Tower"
  products_AutomationAI: "Automation.AI"
  products_Automic_Docs_URL: "https://docs.automic.com/documentation"
  products_Automic_SaaS: "Automic SaaS"
  products_Avaloq: "Avaloq"
  products_BSA: "Broadcom Software Academy"
  products_Broadcom: "Broadcom"
  products_Broadcom_ALLCAPS: "BROADCOM"
  products_CASC: "Service Catalog"
  products_CASC_Plugin: "Service Catalog Plug‑in"
  products_CA_Service_Mgmt: "Service Management"
  products_CV: "Process Analytics"
  products_DLC: "https://downloads.automic.com/"
  products_DXI: "DX Operational Intelligence"
  products_DXI_FirstMention: "(Undefined variable: Products.DXI_FirstMention)"
  products_DXP: "DX Platform"
  products_ESA: "Broadcom Software Academy"
  products_Email_Agent: "Email Agent"
  products_Email_Integration: "Email Integration"
  products_Environment_Manager: "Infrastructure Manager"
  products_EventEngine: "Event Engine"
  products_GCC: "Google Cloud Composer"
  products_GCC_short: "GC Composer"
  products_GCP_DataFusion: "GCP Data Fusion"
  products_GCP_DataFusion_short: "Data Fusion"
  products_GCP_Dataflow: "GCP Dataflow"
  products_GCP_Dataflow_short: "Dataflow"
  products_GenAI: "Gen AI"
  products_Google_Dataproc_long: "Google Dataproc"
  products_ICE_Admin_long: "Lattice Admin tool"
  products_ICE_Admin_short: "Lattice Admin Tool"
  products_ICE_Custom: "Custom Content"
  products_ICE_Custom_Long: "Automic Automation Custom Help"
  products_ICE_long: "Automic Automation Help"
  products_ICE_short: "Help"
  products_Java_API: "AE.ApplicationInterface"
  products_LRT: "License Reporting Tool"
  products_Lambda: "Lambda"
  products_LdapSync: "LDAP Sync"
  products_Marketplace: "https://marketplace.automic.com/"
  products_OAuth: "OAuth"
  products_PCO: "Policy Orchestrator"
  products_PDA: "Predictive Analytics"
  products_PROXY: "Proxy"
  products_PackMgr: "Package Manager"
  products_PackMgr_short: "APM"
  products_PlatformName: "Automic system"
  products_PlatformName_TitleCase: "Automic System"
  products_PluginManager: "Plugin Manager"
  products_RA: "Rapid Automation"
  products_RA_BANNER: "RA Banner Agent"
  products_RA_BO: "RA Business Objects Agent"
  products_RA_FTP: "RA FTP Agent"
  products_RA_HADOOP: "RA Hadoop Agent"
  products_RA_HYPERION_EPMA: "RA Hyperion EPMA Agent"
  products_RA_HYPERION_ESSBASE: "RA Hyperion ESSBASE Agent"
  products_RA_HYPERION_FDMEE: "RA Hyperion FDMEE Agent"
  products_RA_HYPERION_FM: "RA Hyperion FM Agent"
  products_RA_HYPERION_PLANNING: "RA Hyperion Planning Agent"
  products_RA_INFORMATICA: "RA Informatica Agent"
  products_RA_JDE: "RA JD Edwards Agent"
  products_RA_JMS: "RA JMS Agent"
  products_RA_OPALIS: "RA Microsoft Opalis Agent"
  products_RA_ORACLE_BUSINESS: "RA Oracle E-Business Suite Agent"
  products_RA_ORACLE_RETAIL: "RA Oracle Retail Agent"
  products_RA_Oracle_ERP_Cloud: "RA Oracle ERP Cloud Agent"
  products_RA_WEBSERVICE_REST: "RA Web Service REST Agent"
  products_RA_WEBSERVICE_SOAP: "RA Web Service SOAP Agent"
  products_RA_short: "RA"
  products_RM: "Request Manager"
  products_RM_short: "RM"
  products_S3: "Simple Storage Service"
  products_S3_short: "S3"
  products_SAPI: "Service API"
  products_SAP_Data_Intelligence: "SAP Data Intelligence"
  products_SNSC: "ServiceNow Service Connector"
  products_SVO: "Service Orchestrator"
  products_UIM: "Unified Infrastructure Management"
  products_UIM_short: "UIM"
  tools_AIAssistant: "Automation Assistant"
  tools_CAU: "Centralized Agent Upgrade (CAU)"
  tools_CAU_short: "CAU"
  tools_Chatbot: "Intelligent Assistant"
  tools_CompChecker: "compatibility matrix"
  tools_Gateway: "TLS Gateway"
  tools_IMRESTAPIPort: "9000 TCP"
  tools_Installer: "ONE Installer"
  tools_Scripting: "Automation Engine scripting language"
  tools_ZDU: "Zero Downtime Upgrade"
  tools_ZDU_short: "ZDU"
  uIElements_ARA_Perspective: "Release Automation"
  uIElements_Administration: "Administration"
  uIElements_ProcessAssembly: "Process Assembly"
  uIElements_ProcessMonitoring: "Process Monitoring"
  uIElements_SC: "My Catalog"
  uIElements_VersionManagement: "Version Control"
